// Precompiles views/*.ejs into dist/views.js for Cloudflare Workers.
// Workers disallow eval/new Function, which EJS uses at render time.
// Runs automatically via the "build" command in wrangler.jsonc.
const fs = require('fs')
const path = require('path')
const ejs = require('ejs')

const viewsDir = path.join(__dirname, '..', 'views')
const outFile = path.join(__dirname, '..', 'dist', 'views.js')

// Every local variable the templates read; strict mode (no `with`) needs them declared
const locals = ['title', 'page', 'error', 'success', 'nonce']

function listTemplates(dir) {
    return fs.readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
        const fullPath = path.join(dir, entry.name)
        if (entry.isDirectory()) return listTemplates(fullPath)
        return entry.name.endsWith('.ejs') ? [fullPath] : []
    })
}

let output = '// Generated by scripts/build-views.js - do not edit\nconst templates = Object.create(null)\n'

for (const file of listTemplates(viewsDir)) {
    const name = path.relative(viewsDir, file).replace(/\\/g, '/').replace(/\.ejs$/, '')
    const fn = ejs.compile(fs.readFileSync(file, 'utf8'), {
        client: true,
        strict: true,
        compileDebug: false,
        destructuredLocals: locals,
        filename: file
    })
    output += `templates[${JSON.stringify(name)}] = ${fn.toString()}\n`
}

output += 'export default templates\n'

fs.mkdirSync(path.dirname(outFile), { recursive: true })
fs.writeFileSync(outFile, output)
console.log(`Precompiled views -> ${path.relative(process.cwd(), outFile)}`)
